### ISSUE TITLE
Executable paths not found

### ISSUE THREAD

**Issue by hlasimpk** [fsimkovic/pyjob#18]
## System information

- PyJob version: 0.2.0
- Python version: ccp4-python
- Environment (if applicable): CCP4

## Problem description

When running cexec I get a `PyJobExecutableNotFoundError`. 

This seems to come from the line in `cexec`: 

``` python
if not os.path.isfile(cmd[0]):
        raise PyJobExecutableNotFoundError('Cannot find executable: %s' % cmd[0])
```

Commenting the line out bypasses the problem. At first glance the error appears to arise because we're giving just the executable name rather than the full path to the executable. Therefore it searches the directory you're running the job in for the executable. 

## Example

```python
#!/usr/bin/env ccp4-python

import cexec
from pyjob.platform import EXE_EXT

stdout = cexec(['pdbcur' + EXE_EXT], permit_nonzero=True)
```

## Traceback

```python-traceback
     stdout = cexec(['pdbcur' + EXE_EXT], permit_nonzero=True)
cexec
   raise PyJobExecutableNotFoundError('Cannot find executable: %s' % cmd[0])
PyJobExecutableNotFoundError: Cannot find executable:  pdbcur.exe
```

**Comment by hlasimpk** [comment]
Hmm, i'm also getting an error after this point where the MR log file can't be found, again using `os.path.isfile()`, despite the fact that the log file exists.

**Comment by fsimkovic** [comment]
Thanks for reporting the issue. Could you try in SIMBAD to add the full path for `pdbcur.exe` to see if it resolves the issue? I could try and infer the absolute path in `pyjob` with `os.path.abspath` but that does not guarantee to find what you’re looking for.

**Comment by hlasimpk** [comment]
Can confirm that giving the full path to the pdbcur executable does work, and that using `os.path.abspath` doesn't.  We could add a note to cexec explaining that the full path is needed for windows or alternatively we could remove the call to check that the executable is a file and raise an error when the job fails.

**Comment by fsimkovic** [comment]
Okay, that's good to know. Could you try the following:

```bash
$ ccp4-python
>>> import subprocess
>>> subprocess.call(['pdbcur.exe'])
 
 ###############################################################
 ###############################################################
 ###############################################################
 ### CCP4 7.0.061: PDBCUR           version 7.0.061 :         ##
 ###############################################################
 User: felix  Run date:  2/ 9/2018 Run time: 21:30:46 


 Please reference: Collaborative Computational Project, Number 4. 2011.
 "Overview of the CCP4 suite and current developments". Acta Cryst. D67, 235-242.
 as well as any specific reference in the program write-up.

 ***** ERROR #43 READ:

 Logical file name not found.

1
```
This should print something like above to `STDOUT`, could you please confirm?

**Note, do not use the absolute path.**

**Comment by hlasimpk** [comment]
Can confirm that it prints out Logical file name not found

**Comment by hlasimpk** [comment]
Tested 494d508 on windows and the full executable path is now being found.
