### ISSUE TITLE
Queue terminates before the jobs have finished running.  

### ISSUE THREAD

**Issue by hlasimpk** [fsimkovic/pyjob#19]
## System information

- PyJob version: 0.2.0
- Python version: ccp4-python
- Environment (if applicable): CCP4

## Problem description

When running the SIMBAD lattice example I was getting a message suggesting no results were found. Looking into the debug file showed that the MR log couldn't be found which was odd because the log file did exist. 

I was able to find the log files by adding in a sleep command after the job queue was set running as so:
```python
        j = Job(submit_qtype)
        j.submit(
            run_scripts,
            directory=self.output_dir,
            nproc=nproc,
            name='simbad_mr',
            queue=submit_queue,
            permit_nonzero=True)

        interval = int(numpy.log(len(run_scripts)) / 3)
        interval_in_seconds = interval if interval >= 5 else 5
        if process_all:
            j.wait(interval=interval_in_seconds, monitor=monitor)
        else:
            j.wait(interval=interval_in_seconds, monitor=monitor, check_success=mr_succeeded_log)

        import time
        time.sleep(60)

        mr_results = []
        for result, mr_logfile, mr_pdbout, ref_logfile in zip(results, mr_logfiles, mr_pdbouts, ref_logfiles):
            if not os.path.isfile(mr_logfile):
                logger.debug("Cannot find %s MR log file: %s", self.mr_program, mr_logfile)
                continue
            elif not os.path.isfile(ref_logfile):
                logger.debug("Cannot find %s refine log file: %s", self.mr_program, ref_logfile)
                continue
            elif not os.path.isfile(mr_pdbout):
                logger.debug("Cannot find %s output file: %s", self.mr_program, mr_pdbout)
                continue
```

To me this suggests that the wait command isn't working the way we expect it to.

**Comment by hlasimpk** [comment]
Whilst trying to debug this I thought it might have something to do with the `check_success` function, however, when running this with `--process_all` set to avoid calling `check_success` I still get the same problem.

**Comment by hlasimpk** [comment]
Oh, following it back, `local.LocalTask` doesn't have a wait element or a check solution element.

**Comment by hlasimpk** [comment]
Okay followed this all the way back and I think the `self.completed` function in `task.py` doesn't work. Going to try and figure out exactly what is going wrong here and see if I can fix it.

**Comment by fsimkovic** [comment]
Thanks for reporting, could you provide a minimal example that reproduces your error? Maybe outside of SIMBAD? This would help massively.

**Comment by hlasimpk** [comment]
Try this:

```
#!/usr/bin/env ccp4-python

import os
from pyjob import Job
from pyjob.misc import make_script

log = 'logfile.log'

cmd = ['sleep 10 && echo Foo >> ', log]

run_script = make_script(cmd, directory=os.getcwd())
run_scripts = [run_script]

j = Job('local')
j.submit(run_scripts, directory=os.getcwd(), nproc=1, name='test',
         queue=None, permit_nonzero=True)
j.wait(interval=5, monitor=None)

if os.path.isfile(log):
    print('Everything is working as expected')
else:
    raise RuntimeError('Terminated early')
```

**Comment by fsimkovic** [comment]
Thanks for the example, I can confirm the `wait` function does not properly wait and that's based on the `LocalTask.info` call.

**Comment by fsimkovic** [comment]
Could you checkout the latest version and rerun your example to confirm this is fixed?

**Comment by hlasimpk** [comment]
Can confirm this works now on both Mac OS and windows.
