### ISSUE TITLE
Missing README.md in PyPI distribution

### ISSUE THREAD

**Issue by mobiusklein** [fsimkovic/pyjob#5]
## System information
- PyJob version: 0.1.4
- Python version: 2.7.14

## Problem description

The distribution uploaded to PyPI fails to install using `pip` because [setup.py](https://github.com/fsimkovic/pyjob/blob/master/setup.py#L18) script depends upon the presence of the `README.md` file being present, but the hosted tarball doesn't contain it. A MANIFEST file needs to be provided to tell `setuptools` to include it.

## Example

```bash
pip install pyjob
```

## Traceback

```python
  Downloading pyjob-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/scratch/pip-build-EsodyP/pyjob/setup.py", line 35, in <module>
        LONG_DESCRIPTION = readme()
      File "/scratch/pip-build-EsodyP/pyjob/setup.py", line 18, in readme
        with open('README.md', 'r') as f_in:
    IOError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /scratch/pip-build-EsodyP/pyjob/
```

**Comment by fsimkovic** [comment]
Thanks for pointing this out! Addressed in 6f68786bd9f1645fbf8c419681b0c829e95912a1. Version 0.1.5 should work.
