### ISSUE TITLE
UnicodeDecodeError with cexec

### ISSUE THREAD

**Issue by hlasimpk** [fsimkovic/pyjob#6]
## System information

- PyJob version: 0.1.5
- Python version: ccp4-python
- Environment (if applicable): CCP4 7.0.59

## Problem description

When trying to run a new executable through cexec, I get a `UnicodeDecodeError`. This seems to be specific to the new executable, but the following fix does get around the problem:

```python
try:
    stdout = stdout.decode()
except UnicodeDecodeError:
    logger.debug("Ignoring UnicodeDecodeError")
```

## Example

```python
from pyjob import cexec
cmd = [
    'csheetbend',
    '--pdbin', '1DTX_mr_output.pdb',
    '--mtzin', '1DTX_mr_output.mtz', 
    '--pdbout', sheetbend.pdb', 
    '--colin-fo', 'FTOXD3,SIGFTOXD3',
    '-cycles', '100',
    '-resolution-by-cycle', '6,6,3'
]
stdout = cexec(cmd)
```

## Traceback

```python-traceback
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    cexec(cmd)
  File "/home/hlasimpk/ccp4-7.0/lib/py2/site-packages/pyjob/__init__.py", line 76, in cexec
    stdout = stdout.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 919: ordinal not in range(128)
```

**Comment by fsimkovic** [comment]
Good spot! The issue relates to a non-ASCII character in `stdout`, which is not an encoded [`str`](https://docs.python.org/3.6/library/functions.html#str) in form of a [`bytes`](https://docs.python.org/3.6/library/functions.html#bytes) data object returned by [`subprocess.Popen.communicate`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate). A fix has been implemented in 615d0f55fe9c138a584590c927974eef054fd374 and improved in b98bef04a3c03e14d48bbfe58f3d7698b3dac659.
